---
kind: pipeline
name: go-1-11

workspace:
  base: /go
  path: src/github.com/octocat/hello-world

steps:
- name: test
  image: golang:1.11
  commands:
  - go get
  - go test

---
kind: pipeline
name: go-1-10

workspace:
  base: /go
  path: src/github.com/octocat/hello-world

steps:
- name: test
  image: golang:1.10
  commands:
  - go get
  - go test

---
